cloud:
  aws:
    credentials:
      access-key: AKIARDZ3MGFE73UXXNW2
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: pshoo-storage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

